apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp-namespace
data:
  MYSQL_DATABASE: bankAppDB 
  MYSQL_HOST: mysql-service
  MYSQL_USER: root
  MYSQL_PORT: "3306"
  OLLAMA_URL: https://ollama:11434