apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-claim
   namespace: bankapp-namespace
spec:
    accessModes:
       - ReadWriteOnce
    storageClassName: manual
    resources:
        requests:
           storage: 5Gi
    selector:
        matchLabels:
            app: mysql